### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by PatienceKunihira**
i have added the name fp please view it and merge

### CODE REVIEW

**Comment by Otimkev** [comment]
thank you! good work.

**Comment by Otimkev** [comment]
hello, there patience, i won't be able to come today, but you could work with meleby, on the content to be put in the forms.

**Comment by PatienceKunihira** [comment]
Hey Kevin..
Sorry I hadn't seen this email until now. But now I guess its too late so
we shall work on it tomorrow in class.

**Comment by Otimkev** [comment]
It's okay, we will work on it tomorrow. i am doing some work on the menu bar with the icons of the different categories of produce.

**Pull request merged**
